#!/bin/sh
if [ "$1" = "remove" ]; then
	rm -rf /usr/lib/enigma2/python/Plugins/Extensions/TVMagazineCockpit > /dev/null 2>&1
	echo "Plugin removed successfully."
else
	find /usr/lib/enigma2/python/Plugins/Extensions/TVMagazineCockpit -type f -name "*.pyc" -exec rm -f {} \; > /dev/null 2>&1
fi
exit 0
