#!/bin/sh
echo "***********************************"
echo "*       TVMagazineCockpit         *"
echo "*              by                 *"
echo "*          xcentaurix             *"
echo "***********************************"
echo ""
echo "Plugin successfully installed."
echo "Please restart Enigma2 now!"
exit 0
